/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoProject;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testSomeLibraryMethod() {
        App classUnderTest = new App();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someMethod());
    }
}
